spring:
  application:
    name: itoken-config #别名
  boot:
    admin:
      client: #服务监控客户端
        url: http://localhost:8084
  cloud:
    config: #分布式配置中心
      label: master
      server:
        git:
          uri: https://github.com/moxuan-meng/itoken-config.git
          search-paths: respo
          username: 953264802@qq.com
          password: meng0215lk
  zipkin: #配置追踪服务
    base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl: #服务注册与发现 客户端
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info